name: Create packages WSA with Magisk and GAPPS

on:
  push:
    branches:
      - main

jobs:
  build_WSA:
    name: Create packages WSA with Magisk and GAPPS
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      
    env:
      RELEASE_VERSION: '2308.40000.3.0'  # Definisikan variabel RELEASE_VERSION di sini
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main
        repository: YT-Advanced/WSA-Script

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt install -y lzip wine winetricks patchelf e2fsprogs aria2 python3 python3-pip aria2 p7zip-full attr unzip whiptail qemu-utils python3-venv python3-pip p7zip-full

    - name: Run.sh 
      run: |
        cd scripts
        ./build.sh --arch x64 --release-type WIF --magisk-ver stable --gapps-brand MindTheGapps --root-sol magisk --custom-model redfin --compress-format 7z

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: output/*.7z

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pastikan Anda sudah menyediakan GitHub token
      with:
        tag_name: v${{ env.RELEASE_VERSION }}  # Menggunakan variabel RELEASE_VERSION
        release_name: Release version ${{ env.RELEASE_VERSION }}  # Menggunakan variabel RELEASE_VERSION

    - name: Upload Release Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pastikan Anda sudah menyediakan GitHub token
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/WSA_${{ env.RELEASE_VERSION }}_x64_Release-Nightly-with-Magisk-26.3-stable-MindTheGapps-13.0-as-Pixel-5.7z
        asset_name: WSA_${{ env.RELEASE_VERSION }}_x64_Release-Nightly-with-Magisk-26.3-stable-MindTheGapps-13.0-as-Pixel-5.7z  # Menggunakan variabel RELEASE_VERSION
        asset_content_type: application/x-7z-compressed
        
