name: Create packages WSA with Magisk and GAPPS

on:
  push:
    branches:
      - main

jobs:
  build_WSA:
    name: Create packages WSA with Magisk and GAPPS
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main
        repository: YT-Advanced/WSA-Script

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt install -y lzip wine winetricks patchelf e2fsprogs aria2 python3 python3-pip aria2 p7zip-full attr unzip whiptail qemu-utils python3-venv python3-pip p7zip-full

    - name: Run.sh 
      run: |
        cd scripts
        ./build.sh --arch x64 --release-type WIF --magisk-ver stable --gapps-brand MindTheGapps --root-sol magisk --compress-format 7z 

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        path: output/*.7z

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pastikan Anda sudah menyediakan GitHub token

      with:
        tag_name: v2206  # Ganti dengan tag yang sesuai dengan versi yang diunggah
        release_name: Release version 2206  # Nama rilis yang ingin ditampilkan
        draft: false
        prerelease: false

    - name: Upload Release Artifact
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pastikan Anda sudah menyediakan GitHub token

      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: output/*.7z
        asset_name: wsa-artifact.7z
        asset_content_type: application/x-7z-compressed
